openapi: '3.0.0'

info:
  title: sls-medicines-api
  version: 1.0.0

paths:
  /product/{eans}:
    get:
      operationId: product
      summary: List API versions
      responses:
        '200':
          description: |-
            200 response
          content:
            application/json:
              examples:
                foo:
                  value:
                    {
                      'versions':
                        [
                          {
                            'status': 'CURRENT',
                            'updated': '2011-01-21T11:33:21Z',
                            'id': 'v2.0',
                            'links':
                              [
                                {
                                  'href': 'http://127.0.0.1:8774/v2/',
                                  'rel': 'self',
                                },
                              ],
                          },
                          {
                            'status': 'EXPERIMENTAL',
                            'updated': '2013-07-23T11:33:21Z',
                            'id': 'v3.0',
                            'links':
                              [
                                {
                                  'href': 'http://127.0.0.1:8774/v3/',
                                  'rel': 'self',
                                },
                              ],
                          },
                        ],
                    }
        '300':
          description: |-
            300 response
          content:
            application/json:
              examples:
                foo:
                  value: |
                    {
                     "versions": [
                           {
                             "status": "CURRENT",
                             "updated": "2011-01-21T11:33:21Z",
                             "id": "v2.0",
                             "links": [
                                 {
                                     "href": "http://127.0.0.1:8774/v2/",
                                     "rel": "self"
                                 }
                             ]
                         },
                         {
                             "status": "EXPERIMENTAL",
                             "updated": "2013-07-23T11:33:21Z",
                             "id": "v3.0",
                             "links": [
                                 {
                                     "href": "http://127.0.0.1:8774/v3/",
                                     "rel": "self"
                                 }
                             ]
                         }
                     ]
                    }
components:
  schemas:
    Product:
      type: object
      properties:
        _key:
          type: string
        eans:
          type: string[]
        name:
          type: string
        manufacturerCnpj:
          type: string
        manufacturer:
          type: string
        imageUrl:
          type: string
        tarja:
          type: string
        details:
          type: string
        active:
          type: number
        generic:
          type: boolean
        apresentacao_manual:
          type: string
        descricao_manual:
          type: string
        apresentacao_tuss:
          type: string
        apresentacao_anvisa:
          type: string
        qtde_apresentacao:
          type: number
        apresentacao_menor:
          type: string
        substancia:
          type: string
        indicacao:
          type: string
        max_price:
          type: number
        min_price:
          type: number
        bula_not_found:
          type: boolean
        antibiotic:
          type: boolean
        link_bula:
          type: strin
        manufacturer_sac:
          type: string
        manufacturer_email:
          type: string
        indicado_para:
          type: string
        desativado_manualmente:
          type: string

        categoria:
          type: string[]
